# Restar m de n en unario: entrada n ceros, 'C', m ceros
input: '000C00000'
blank: 'B'
start state: q0
table:
  q0:
    0: {write: X, R: q1}
    X: {write: X, L: q5}
  
  q1:
    0: {write: 0, R}
    X: {write: X, R}
    C: {write: C, R: q2}
  
  q2:
    0: {write: 0, R}
    B: {L: q3}

  q3:
    0: {write: B, L: q4}

  q4:
    0: {write: 0, L}
    C: {write: C, L: q0}

  q5:
    X: {write: X, L}
    0: {write: X, L: q1}
    B: {write: B, R: q6}

  q6:
    X: {write: B, R}
    C: {write: B, R}
    # Estado final
